### ISSUE TITLE
Basic functionality failed with Java error on macos 

### ISSUE THREAD

**Issue by shivam-anand-s1** [Hakky54/certificate-ripper#13]
**Describe the bug**
crip print --url=https://stackoverflow.com failed, added logs

**Environmental Data:**
- Apple M1 Pro with Ventura 13.1

**logs**
```bash
crip print --url=https://stackoverflow.com 
```
```bash   
nl.altindag.ssl.exception.GenericCertificateException: java.net.ConnectException: Operation timed out
	at nl.altindag.ssl.util.CertificateExtractorUtils.getCertificatesFromRemoteFile(CertificateExtractorUtils.java:197)
	at nl.altindag.ssl.util.CertificateExtractorUtils.getRootCaFromAuthorityInfoAccessExtensionIfPresent(CertificateExtractorUtils.java:172)
	at nl.altindag.ssl.util.CertificateExtractorUtils.getRootCaIfPossible(CertificateExtractorUtils.java:154)
	at nl.altindag.ssl.util.CertificateExtractorUtils.getRootCaFromChainIfPossible(CertificateExtractorUtils.java:147)
	at nl.altindag.ssl.util.CertificateExtractorUtils.getCertificateFromExternalSource(CertificateExtractorUtils.java:120)
	at nl.altindag.ssl.util.CertificateUtils.getCertificatesFromExternalSource(CertificateUtils.java:232)
	at nl.altindag.ssl.util.CertificateUtils.lambda$getCertificatesFromExternalSources$4(CertificateUtils.java:275)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.5/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at nl.altindag.ssl.util.CertificateUtils.getCertificatesFromExternalSources(CertificateUtils.java:276)
	at nl.altindag.ssl.util.CertificateUtils.getCertificatesFromExternalSources(CertificateUtils.java:262)
	at nl.altindag.crip.command.SharedProperties.getCertificates(SharedProperties.java:82)
	at nl.altindag.crip.command.SharedProperties.getUrlsToCertificates(SharedProperties.java:53)
	at nl.altindag.crip.command.PrintCommand.run(PrintCommand.java:43)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at nl.altindag.crip.App.main(App.java:26)
Caused by: java.net.ConnectException: Operation timed out
	at java.base@17.0.5/sun.nio.ch.Net.connect0(Net.java)
	at java.base@17.0.5/sun.nio.ch.Net.connect(Net.java:579)
	at java.base@17.0.5/sun.nio.ch.Net.connect(Net.java:568)
	at java.base@17.0.5/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base@17.0.5/java.net.Socket.connect(Socket.java:633)
	at java.base@17.0.5/java.net.Socket.connect(Socket.java:583)
	at java.base@17.0.5/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base@17.0.5/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base@17.0.5/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base@17.0.5/sun.net.www.http.HttpClient.<init>(HttpClient.java:279)
	at java.base@17.0.5/sun.net.www.http.HttpClient.New(HttpClient.java:384)
	at java.base@17.0.5/sun.net.www.http.HttpClient.New(HttpClient.java:406)
	at java.base@17.0.5/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
	at java.base@17.0.5/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base@17.0.5/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base@17.0.5/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
	at java.base@17.0.5/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base@17.0.5/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at nl.altindag.ssl.util.CertificateExtractorUtils.getCertificatesFromRemoteFile(CertificateExtractorUtils.java:186)
	... 27 more
```

**Comment by Hakky54** [comment]
Are you using vpn/proxy?

**Comment by shivam-anand-s1** [comment]
No I'm not behind any VPN

**Comment by Hakky54** [comment]
I tested it with a Mac m1 pro and I didn't get the exception. How did you install crip?

**Comment by shivam-anand-s1** [comment]
```
brew tap hakky54/crip
brew install crip
```
also `brew install crip` forced em to update xcode before installing

**Comment by Hakky54** [comment]
That looks ok. Well when you are running crip with stackoverflow it is also rying to access `http://apps.identrust.com/roots/dstrootcax3.p7c` under the covers and there it is somehow failing. It does not happen in my testing environment, but maybe that url is somehow blocked by your internet provider, router or on your mac. Can you just open that link through your browser and see if your browser is downloading a `dstrootcax3.p7c` file?
