### ISSUE TITLE
Doesn't work in a container

### ISSUE THREAD

**Issue by mimmus** [Hakky54/certificate-ripper#15]
**Describe the bug**
cript doesn't work inside a container (running on kubernetes)

**To Reproduce**
```
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Container.metrics(Container.java:44)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:177)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.heap.PhysicalMemory.doInitialize(PhysicalMemory.java:145)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.heap.PhysicalMemory.size(PhysicalMemory.java:88)
        at java.base@17.0.5/java.lang.Runtime.maxMemory(Runtime.java:896)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.DirectMemoryAccessors.initialize(Target_jdk_internal_misc_VM.java:120)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.DirectMemoryAccessors.getPageAlignDirectMemory(Target_jdk_internal_misc_VM.java:102)
        at java.base@17.0.5/jdk.internal.misc.VM.isDirectMemoryPageAligned(VM.java:147)
        at java.base@17.0.5/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
        at java.base@17.0.5/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332)
        at java.base@17.0.5/sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:243)
        at java.base@17.0.5/sun.nio.ch.NioSocketImpl.tryWrite(NioSocketImpl.java:394)
        at java.base@17.0.5/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:413)
        at java.base@17.0.5/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
        at java.base@17.0.5/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
        at java.base@17.0.5/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
        at java.base@17.0.5/sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:271)
        at java.base@17.0.5/sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:89)
        at java.base@17.0.5/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:646)
        at java.base@17.0.5/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:529)
        at java.base@17.0.5/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:112)
        at java.base@17.0.5/sun.security.ssl.TransportContext.kickstart(TransportContext.java:251)
        at java.base@17.0.5/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
        at java.base@17.0.5/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at java.base@17.0.5/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
        at java.base@17.0.5/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
        at java.base@17.0.5/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
        at nl.altindag.ssl.util.CertificateExtractorUtils.getCertificateFromExternalSource(CertificateExtractorUtils.java:117)
        at nl.altindag.ssl.util.CertificateUtils.getCertificatesFromExternalSource(CertificateUtils.java:232)
        at nl.altindag.ssl.util.CertificateUtils.lambda$getCertificatesFromExternalSources$4(CertificateUtils.java:275)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.5/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at nl.altindag.ssl.util.CertificateUtils.getCertificatesFromExternalSources(CertificateUtils.java:276)
        at nl.altindag.ssl.util.CertificateUtils.getCertificatesFromExternalSources(CertificateUtils.java:262)
        at nl.altindag.crip.command.SharedProperties.getCertificates(SharedProperties.java:82)
        at nl.altindag.crip.command.SharedProperties.getUrlsToCertificates(SharedProperties.java:53)
        at nl.altindag.crip.command.PrintCommand.run(PrintCommand.java:43)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at nl.altindag.crip.App.main(App.java:26)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)
        ... 52 more
Caused by: java.lang.ExceptionInInitializerError
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupMetrics.getInstance(CgroupMetrics.java:164)
        ... 54 more
Caused by: java.lang.NullPointerException
        at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base@17.0.5/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.lambda$readStringValue$0(CgroupUtil.java:57)
        at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:144)
        at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:59)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
        ... 56 more

```

**Environmental Data:**
- OS (Windows/Linux/MacOS)
Ubuntu 22.04.2 LTS

**Comment by Hakky54** [comment]
Can you provide me an example container with a script to reproduce it on my side?

**Comment by mimmus** [comment]
Official Ubuntu. I ran with:
`kubectl run ubuntu --image=ubuntu  --rm -i --tty -- /bin/bash`

**Comment by Hakky54** [comment]
I just tried it out locally with kubectl and it works. What I have done is:

1. Install docker
2. Install kubectl
3. Install minicube
4. Start minicube: on the terminal `minikube dashboard`
5. Download crip binary for linux amd64: https://github.com/Hakky54/certificate-ripper/releases/download/2.1.0/crip-linux-amd64.tar.gz
6. Extract it locally: `tar -xzf crip-linux-amd64.tar.gz`
7. Start ubuntu in a new terminal: `kubectl run ubuntu --image=ubuntu  --rm -i --tty -- /bin/bash`
8. Copy crip into pod in another terminal:  
9. kubectl cp Downloads/crip ubuntu:/crip
10. In the ubuntu pod just run: `./crip print -u https://stackoverflow.com`

Can you retry on your side with these steps?

```

```

**Comment by Hakky54** [comment]
See below also the screenshot of the ubuntu pod where I exported the certificates in a p12 file and as binary individual files. <img width="1055" alt="Screenshot 2023-06-07 at 15 23 14" src="https://github.com/Hakky54/certificate-ripper/assets/16032204/2c3e3da5-f779-4ecd-9e26-d6a277138c7f">

**Comment by mimmus** [comment]
Probably, it depends from cgroup type (v1/v2) + Java version but I haven't the knowledge to investigate further.

**Comment by mimmus** [comment]
https://bugs.openjdk.org/browse/JDK-8258954

**Comment by Hakky54** [comment]
Hmm, but why are you using it with Java while you can also use native executables?

**Comment by Hakky54** [comment]
>  https://bugs.openjdk.org/browse/JDK-8258954

Well looking at the bug report it seems like the issue was present in Java 15 and it was fixed in Java 16. You are using GraalVM as Java Runtime Environment which is based on Java 17, so I would assume that it is working however it seems like it is not... So I would suggest to raise an issue on the github page of graal: https://github.com/oracle/graal/issues

So what I have done is installed graalvm-ce-java17-22.3.2 on the ubuntu container in kubernetes. Grabbed the certificate ripper jar from the release package and it works. I am not getting the same exceptions as you. See below for the screenshot:

<img width="1055" alt="Screenshot 2023-06-08 at 02 15 36" src="https://github.com/Hakky54/certificate-ripper/assets/16032204/94e0cdec-5069-48fb-b59a-923e1f12b2db">

So it seems like the bug was indeed fixed in Java 17 with GraalVM, but it is strange that you are getting that error. I would suggest to raise an issue on the github page of graal: https://github.com/oracle/graal/issues as it is not related to certificate ripper and I think they would be able to support you with this issue.

An alternative would be using the native os executable for Linux of Certificate Ripper as it does not need the JVM. It will be faster, use less memory etc.

**Comment by mimmus** [comment]
As said, I'm using the native executable!

But it is not really an issue: I was trying 'crip' from inside a container to debug a cluster internal service. but solved in other ways.

Thank you for your time

T

**Comment by Hakky54** [comment]
> As said, I'm using the native executable

Ah, my apologies I had the idea that you were using the jar file.

Glad that it is now working for you. What was your workaround by the way?

**Comment by Hakky54** [comment]
Aha, so it will stay a mystery. Then I am closing this is issue as I could not replicate it on my side
